spring:
  application:
    name: example-FeignDemo
server:
  port: 10186

# 自定义OpenFeign的参数
my-feign:
  # 微服务的标题
  title: FeignDemo微服务调用Demo微服务API文档
  # 微服务的描述
  description: 本文档描述了DemoFeign微服务接口定义
  # Feign版本
  version: 1.0
  # 联系方式
  contact:
    name: xxx
    url: http://XXX.com
    email: xxx@qq.com
